FROM jupyterhub/jupyterhub

#ADD settings/jupyter_notebook_config.py /etc/jupyter/
#ADD settings/jupyterhub_config.py /etc/jupyterhub/
ADD StartHere.ipynb /etc/skel
COPY scripts /scripts

RUN chmod -R 755 /scripts
#RUN jupyter trust /etc/skel/StartHere.ipynb
    
EXPOSE 8000

CMD "/scripts/sys/init.sh"
