FROM ubuntu:19.04

RUN apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        sudo \
        software-properties-common apt-transport-https \
        zip \
        tzdata locales \
        bash-completion man-db \
        neovim git \
        rsync curl

# create /workdir
RUN mkdir -p /workdir && chmod 777 /workdir

RUN apt-get install -y \
        python3 python3-pip python3-venv \
        python3-all-dev python3-setuptools build-essential python3-wheel \
    && curl -sSL www.legendu.net/media/install_py_github.py | python3 - https://github.com/dclong/xinstall --sys \
    && curl -sSL www.legendu.net/media/install_py_github.py | python3 - https://github.com/dclong/dsutil --sys \
    && pip3 install mypy pylint yapf pytest ipython

RUN pip3 install --no-cache-dir tornado jupyter nbdime

RUN apt-get install -y --no-install-recommends \
        nodejs npm \
    && npm install -g n \
    && n 12.13.0

RUN pip3 install --no-cache-dir jupyterlab \
      jupyter-lsp python-language-server[all] \
    && jupyter labextension install @jupyter-widgets/jupyterlab-manager \
    && jupyter labextension install @jupyterlab/toc \
    && jupyter labextension install jupyterlab-favorites \
    && jupyter labextension install jupyterlab-recents \
    && jupyter labextension install @krassowski/jupyterlab-lsp \
    && npm cache clean --force

RUN npm install -g configurable-http-proxy \
    && pip3 install --no-cache-dir jupyterhub \
    && npm cache clean --force

ADD settings/jupyter_notebook_config.py /etc/jupyter/
ADD settings/jupyterhub_config.py /etc/jupyterhub/
#ADD scripts /scripts
#COPY scripts /scripts

#Tensorflow
RUN pip3 install torch torchvision tensorflow keras h2o gensim pytext-nlp

#Julia
RUN apt-get install -y julia  && \
    julia -e 'empty!(DEPOT_PATH); push!(DEPOT_PATH, "/usr/share/julia"); using Pkg; Pkg.add("IJulia")'  && \
    cp -r /root/.local/share/jupyter/kernels/julia-* /usr/local/share/jupyter/kernels/  && \
    chmod -R +rx /usr/share/julia/  && \
    chmod -R +rx /usr/local/share/jupyter/kernels/julia-*/

#Javascript
RUN npm install -g --unsafe-perm ijavascript && ijsinstall --hide-undefined --install=global

#Typescript
RUN npm install -g --unsafe-perm itypescript && its --ts-hide-undefined --install=global

#C++
RUN apt-get install -y libtinfo5 wget && \
    mkdir -p ~/pre && cd ~/pre && \
    wget https://root.cern.ch/download/cling/cling_2019-12-08_ubuntu18.tar.bz2 && \
    tar jxf cling_2019-12-08_ubuntu18.tar.bz2 && \
    cd cling_2019-12-08_ubuntu18 && \
    cp -r . /usr/. && \
    cd ~ && rm -r pre && \
    cd /usr/share/cling/Jupyter/kernel && \
    pip3 install -e . && \
    jupyter kernelspec install cling-cpp11 && \
    jupyter kernelspec install cling-cpp14 && \
    jupyter kernelspec install cling-cpp17 && \
    jupyter kernelspec install cling-cpp1z && \
    cp /usr/share/cling/Jupyter/kernel/cling.ipynb /workdir

#Bash
RUN pip3 install bash_kernel && python3 -m bash_kernel.install

#Markdown
RUN pip3 install markdown-kernel && python3 -m markdown_kernel.install

#Java
RUN apt-get install -y openjdk-8-jdk && \
    apt-get install -y maven gradle
    
ENV M2_HOME=/usr/share/maven
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin

#Python
RUN pip3 install --no-cache-dir loguru pysnooper numpy scipy pandas pyarrow>=0.14.0 dask[complete] \
        scikit-learn xgboost matplotlib bokeh holoviews[recommended] hvplot \
        tabulate JPype1==0.6.3 JayDeBeApi sqlparse requests[socks] lxml notifiers

RUN jupyter labextension install @pyviz/jupyterlab_pyviz 

#BeakerX
RUN pip3 install --no-cache-dir py4j beakerx && \
    beakerx install && \
    jupyter labextension install @jupyter-widgets/jupyterlab-manager && \
    jupyter labextension install beakerx-jupyterlab
    
COPY scripts /scripts
#RUN npm cache clean --force

RUN chmod -R 755 /scripts
RUN /scripts/sys/create_user_nogroup.sh dave 2000

EXPOSE 8000
