FROM jupyterhub/jupyterhub

ENV DEBIAN_FRONTEND noninteractive

ADD settings/jupyter_notebook_config.py /etc/jupyter/
ADD settings/jupyterhub_config.py /etc/jupyterhub/
COPY scripts /scripts

RUN chmod -R 755 /scripts

CMD "/scripts/sys/init.sh"
